version: "3.9"

services:
  web:
    image: drupal
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - ./src:/var/www/php/drupalville
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'drupalville'
      MYSQL_USER: 'daniel'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./.docker/mysql:/opt/mysql

